### ISSUE TITLE
Alt.Composition.Web.Mvc Session Scoped and User Scoped

### ISSUE THREAD

**Issue by ido-ran** [nblumhardt/alt-composition#2]
Is there a way to bind part to HTTP session?

I always look at Google Guice for comparison and they support bind parts to both request and session.

The CompositionContext that is return from DependencyResolver.Current is the CurrentRequestContext which makes it really hard to make part session or user scoped. Am I wrong?
The problem is that scope should be define in the exporting definition and not from the importing side by accessing the "right" scope CompositionContext.

**Comment by nblumhardt** [comment]
Hi Ido, no, there's no session-scoping support implemented or planned. Using a container-managed component that pulls data from the session is a simpler/more reliable alternative in my experience. Cheers!
